services:
  tiptapphp:
    image: tiptapphp
    build:
      context: plastikatwy-site-backend-7606bba907d3/plastikatwy-site-backend-7606bba907d3/vendor/ueberdosis/tiptap-php
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
